name: Sync with upstream
on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 00:00 执行同步操作
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Sync with upstream
        run: |
          git remote add upstream https://github.com/ufrisk/LeechCore.git
          git fetch upstream
          git checkout master
          git merge upstream/master -m "Sync with upstream"
          git push origin master
